### ISSUE TITLE
Thoughts about visualisation and data 

### ISSUE THREAD

**Issue by chrisyifanjin** [YiranJing/Coronavirus-Epidemic-2019-nCov#3]
Hi, @YiranJing 

[http://github.com/BlankerL/DXY-2019-nCoV-Crawler](url)

这里有三个数据可视化

1:  
http://cuihuan.net/wuhan/news.html  
http://github.com/cuihuan/2020_wuhan

全国数据:
全国 ncov 总数量以及全国 ncov 新增量

我觉得可以把疑似/和确诊放在一起，把死亡和治愈放在一起这样更容易看出来数据的变化。

分省数据: 
还是把疑似/确诊，治愈/死亡这样分成两类

2: 
http://yiqing.ahusmart.com/
https://github.com/hack-fang/nCov

这个图是用中国地图做的。但是只明确了几个省份。我觉得可以做那种 点击哪个省份 然后哪个省份的地图放大，数字具体到各个市，然后把第一个 visualization 的图表也加上，这样又能看到数据变化又能看到实时数量。

3:
https://github.com/Moyck/2019NCOV

这个文件是apk格式，安卓手机应用程序的格式。它有一个光标可以调整日期， 我觉得我们不需要因为我 们可以有时间变化的图标。这个主要是给中老年人看的，所以比较简洁。

API:
https://lab.isaaclin.cn/nCoV/
这个网站有所有dataset的所有变量的description

https://github.com/BlankerL/DXY-2019-nCoV-Data
这个网站里面有所有的数据，包括：
全国数据 DXYOverall.csv
地区数据 DXYArea.csv
新闻数据 DXYNews.csv
谣言数据 DXYRumors.csv

我觉得我们可以用他在丁香园上的数据，选出每天最晚更新的时间的数据作为那天的总数和增量，以天为时间单位去做数据可视化去看总量和增量的变化。

**Comment by YiranJing** [comment]
@chrisyifanjin 嗯嗯，谢谢你的建议，这几个可视化我看了。
1. 和2 的话 我个人更喜欢2 的可视化，不过咱们可以借鉴他们的排版构思，不过tableau可以把总体和各个省份合并在一起，和他们可视化的方式完全不一样。对，可以很容易实现对各个省市

3.
是的 我也赞同咱们应该用这个数据，我在写model。写完之后明天有空再更新这个丁香园数据
